#修改世界书或预设
#启动终端
  - node tavern_sync.mjs

#从酒馆提取世界书
  - node tavern_sync.mjs pull 世界书名字
  - node tavern_sync.mjs pull 中世纪与帝国
  - node tavern_sync.mjs pull 蒸汽异界

#同步修改结果到酒馆
  - node tavern_sync.mjs push 中世纪与帝国 -f

#实时同时修改结果
  - node tavern_sync.mjs watch 中世纪与帝国 -f

# 将世界书/预设推送到酒馆网页, 并从酒馆网页打包文件回本地
  - node tavern_sync.mjs push --export 世界书名字

# 不经过酒馆网页直接打包文件, 因此你甚至不需要开启酒馆网页
  - node tavern_sync.mjs bundle 命定之诗
